title: Nikhil Neelagaru
description: Personal website about various ML/DL/RL projects, statistics, and physics I am working on.
theme: minima
plugins:
  - jekyll-feed
show_excerpts: true
minima:
  social_links: []
header_pages:
  - physics.md
  - machine-learning.md
  - statistics.md
  - other.md
  - puzzles.md
  - travel.md
  - contact.md
  - about.md
markdown: kramdown
kramdown:
  math_engine: mathjax
